// <auto-generated />
namespace EventWarez.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class migrate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrate));
        
        string IMigrationMetadata.Id
        {
            get { return "202106092058389_migrate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
